import { type ItemTemplate, type WeaponSlotPolicy } from "../types"

const asPolicy = (policy: WeaponSlotPolicy) => policy

const ITEMS: Record<string, ItemTemplate> = {
  debug_stick: {
    id: "debug_stick",
    name: "Debug Stick",
    kind: "weapon",
    rarity: "unique",
    weaponSlotPolicy: asPolicy("primaryOnly"),
    weaponCards: {
      // for debugging, this weapon gets all cards from cards.ts
      primary: [
        "aimed_shot",
        "burst_fire",
        "full_auto",
        "counter",
        "hip_fire",
        "smoke_screen",
        "evasive_maneuvers",
        "dodge",
        "recover",
        "recover_plus",
        "energy_surge",
        "burn_away"
      ],
      secondary: [],
    },
  },
  knife_rusty: {
    id: "knife_rusty",
    name: "Rusty Knife",
    kind: "weapon",
    rarity: "common",
    weaponSlotPolicy: asPolicy("either"),
    weaponCards: {
      primary: [],
      secondary: ["flash_focus"],
    },
    tags: ["melee", "blade"],
    effects: [
      { kind: "stat", skills: { subSkills: { closeCombat: 1 } } },
    ],
    description: "A worn blade that still cuts. Works in a pinch.",
  },
  pistol_basic: {
    id: "pistol_basic",
    name: "Service Pistol",
    kind: "weapon",
    rarity: "common",
    weaponSlotPolicy: asPolicy("either"),
    weaponCards: {
      primary: ["int_overload"],
      secondary: ["echo_strike_setup", "hand_count_attack"],
    },
    tags: ["ranged", "pistol"],
    effects: [
      { kind: "stat", skills: { subSkills: { marksmanship: 1 } } },
    ],
    description: "Standard sidearm issued to low-tier security.",
  },
  smg_street: {
    id: "smg_street",
    name: "Street SMG",
    kind: "weapon",
    rarity: "uncommon",
    weaponSlotPolicy: asPolicy("primaryOnly"),
    weaponCards: {
      primary: ["int_overload", "echo_strike_setup", "attack_count_turn"],
      secondary: ["flash_focus"],
    },
    tags: ["ranged", "smg"],
    effects: [
      { kind: "stat", skills: { subSkills: { marksmanship: 1, mobility: 1 } } },
    ],
    description: "Sprays lead fast; control is optional.",
  },
  cleaver_brutal: {
    id: "cleaver_brutal",
    name: "Brutal Cleaver",
    kind: "weapon",
    rarity: "uncommon",
    weaponSlotPolicy: asPolicy("either"),
    weaponCards: {
      primary: ["smash_and_bleed"],
      secondary: ["under_50_double"],
    },
    tags: ["melee", "blade"],
    effects: [{ kind: "stat", skills: { str: 1, subSkills: { closeCombat: 1 } } }],
    description: "Heavy street cleaver that rewards reckless swings.",
  },
  hammer_breacher: {
    id: "hammer_breacher",
    name: "Breacher Hammer",
    kind: "weapon",
    rarity: "rare",
    weaponSlotPolicy: asPolicy("primaryOnly"),
    weaponCards: {
      primary: ["attack_count_combat", "under_50_double"],
    },
    tags: ["melee", "blunt"],
    effects: [{ kind: "stat", skills: { str: 1, subSkills: { athletics: 1 } } }],
    description: "Industrial sledge turned battlefield finisher.",
  },
  smg_cascade: {
    id: "smg_cascade",
    name: "Cascade SMG",
    kind: "weapon",
    rarity: "rare",
    weaponSlotPolicy: asPolicy("primaryOnly"),
    weaponCards: {
      primary: ["wild_barrage", "attack_count_turn"],
      secondary: ["hand_count_attack"],
    },
    tags: ["ranged", "smg"],
    effects: [{ kind: "stat", skills: { subSkills: { marksmanship: 1, mobility: 1 } } }],
    description: "Sprays chaotic volleys that scale with your aggression.",
  },
  medkit_small: {
    id: "medkit_small",
    name: "Medkit (Small)",
    kind: "consumable",
    rarity: "common",
    stackable: true,
    maxStack: 5,
    consumedOnUse: true,
    effects: [
      { kind: "stat", vitals: { health: 20, stress: -5 } },
    ],
    description: "Single-use kit to patch small wounds and steady nerves.",
  },
  energy_snack: {
    id: "energy_snack",
    name: "Energy Snack",
    kind: "consumable",
    rarity: "common",
    stackable: true,
    maxStack: 10,
    consumedOnUse: true,
    effects: [
      { kind: "stat", vitals: { stress: -3 }, skills: { subSkills: { mobility: 1 } } },
    ],
    description: "Sugary rush that helps you keep moving.",
  },
  deadman_switch: {
    id: "deadman_switch",
    name: "Deadman Switch",
    kind: "equipment",
    rarity: "unique",
	equipSlot: "utility",
    stackable: false,
    consumedOnUse: true,
    cardRefs: ["breaker_victory"],
    tags: ["explosive"],
    description: "One-shot fail-safe that ends a fight at the cost of the device.",
  },
  jacket_cloth: {
    id: "jacket_cloth",
    name: "Padded Jacket",
    kind: "equipment",
    rarity: "uncommon",
    equipSlot: "top",
    tags: ["armor"],
    effects: [
      { kind: "stat", vitals: { health: 5, looks: -1 } },
    ],
    description: "Light padding with a questionable fashion sense.",
  },
  pants_reinforced: {
    id: "pants_reinforced",
    name: "Reinforced Pants",
    kind: "equipment",
    rarity: "uncommon",
    equipSlot: "bottom",
    tags: ["armor"],
    effects: [
      { kind: "stat", vitals: { health: 5 }, skills: { subSkills: { mobility: 1 } } },
    ],
    description: "Sturdy trousers with hidden plates for the cautious courier.",
  },
  satchel_courier: {
    id: "satchel_courier",
    name: "Courier Satchel",
    kind: "equipment",
    rarity: "common",
    equipSlot: "utility",
    tags: ["bag", "utility"],
    cardRefs: ["next_turn_draw"],
    description: "Keeps a backup draw ready for the next turn.",
  },
  rig_utility: {
    id: "rig_utility",
    name: "Utility Rig",
    kind: "equipment",
    rarity: "rare",
    equipSlot: "utility",
    tags: ["rig", "utility"],
    passiveCardRefs: ["flash_focus"],
    effects: [
      { kind: "stat", vitals: { popularity: 2 } },
    ],
    description: "Straps and pockets for every tool you own.",
  },
  purge_capacitor: {
    id: "purge_capacitor",
    name: "Purge Capacitor",
    kind: "equipment",
    rarity: "rare",
    equipSlot: "utility",
    tags: ["rig", "energy"],
    cardRefs: ["exhaust_three_energy"],
    description: "Dumps spare cells for a burst of future energy, eating your discard.",
  },
  archive_loop_deck: {
    id: "archive_loop_deck",
    name: "Archive Loop Deck",
    kind: "equipment",
    rarity: "uncommon",
    equipSlot: "utility",
    tags: ["rig", "deck"],
    cardRefs: ["copy_discard_to_deck"],
    description: "Keeps your favorite discard card in rotation by duplicating it.",
  },
  echo_wrist_deck: {
    id: "echo_wrist_deck",
    name: "Echo Wrist Deck",
    kind: "equipment",
    rarity: "rare",
    equipSlot: "utility",
    tags: ["rig", "deck"],
    cardRefs: ["recast_top_discard"],
    description: "Quick-cast module to replay the top discard in combat.",
  },
  trinket_lucky_coin: {
    id: "trinket_lucky_coin",
    name: "Lucky Coin",
    kind: "equipment",
    rarity: "rare",
    equipSlot: "accessory",
    tags: ["lucky"],
    passiveCardRefs: ["flash_focus"],
    effects: [
      { kind: "stat", vitals: { popularity: 1 } },
    ],
    description: "A tarnished coin that seems to bend odds in your favor.",
  },
  charm_blood_oath: {
    id: "charm_blood_oath",
    name: "Blood Oath Charm",
    kind: "equipment",
    rarity: "common",
    equipSlot: "accessory",
    tags: ["occult"],
    cardRefs: ["dot_self"],
    description: "A risky charm that feeds power with your own blood over time.",
  },
  neural_chip_mk1: {
    id: "neural_chip_mk1",
    name: "Neural Chip Mk.I",
    kind: "cybernetic",
    rarity: "rare",
    equipSlot: "neural",
    tags: ["cyber"],
    factionTags: ["corp"],
    cardRefs: ["int_overload", "flash_focus"],
    effects: [
      { kind: "stat", vitals: { humanity: -5 }, skills: { int: 1, subSkills: { hacking: 1 } } },
    ],
    description: "Boosts cognition at the cost of a little soul.",
  },
  load_balancer_mk1: {
    id: "load_balancer_mk1",
    name: "Load Balancer Mk.I",
    kind: "cybernetic",
    rarity: "rare",
    equipSlot: "neural",
    tags: ["cyber"],
    factionTags: ["corp"],
    cardRefs: ["tighten_focus"],
    effects: [{ kind: "stat", vitals: { humanity: -3 }, skills: { int: 1 } }],
    description: "Dynamically tunes focus: fewer cards, more energy each turn.",
  },
  ocular_hud_mk1: {
    id: "ocular_hud_mk1",
    name: "Ocular HUD Mk.I",
    kind: "cybernetic",
    rarity: "uncommon",
    equipSlot: "ocular",
    tags: ["cyber"],
    factionTags: ["corp"],
    cardRefs: ["data_loop"],
    effects: [
      { kind: "stat", skills: { subSkills: { stealth: 1 } } },
    ],
    description: "Overlay data feeds into your vision, enhancing awareness.",
  },
  dermal_weave_i: {
    id: "dermal_weave_i",
    name: "Dermal Weave I",
    kind: "cybernetic",
    rarity: "rare",
    equipSlot: "dermal",
    tags: ["cyber", "armor"],
    effects: [
      { kind: "stat", vitals: { health: 10, looks: -2 } },
    ],
    description: "Subdermal mesh stiffens the skin against impacts.",
  },
  skeletal_brace: {
    id: "skeletal_brace",
    name: "Skeletal Brace",
    kind: "cybernetic",
    rarity: "rare",
    equipSlot: "skeletal",
    tags: ["cyber"],
    effects: [
      { kind: "stat", skills: { subSkills: { athletics: 1 } }, vitals: { health: 5 } },
    ],
    description: "Reinforced frame for heavier loads and stronger blows.",
  },
  systems_overclocker: {
    id: "systems_overclocker",
    name: "Systems Overclocker",
    kind: "cybernetic",
    rarity: "unique",
    equipSlot: "systems",
    tags: ["cyber"],
    passiveCardRefs: ["combat_start_boost"],
    effects: [
      { kind: "stat", vitals: { humanity: -8, stress: 5 }, skills: { subSkills: { hacking: 2 } } },
    ],
    description: "Pushes your neural bus to unsafe speeds. Handle with care.",
  },
  external_drone_link: {
    id: "external_drone_link",
    name: "Drone Link Harness",
    kind: "cybernetic",
    rarity: "rare",
    equipSlot: "external",
    tags: ["cyber", "drone"],
    cardRefs: ["echo_strike_setup"],
    effects: [
      { kind: "stat", skills: { subSkills: { engineering: 1 } } },
    ],
    description: "Tethers your nervous system to a drone swarm interface.",
  },
  net_projector: {
    id: "net_projector",
    name: "Static Net Projector",
    kind: "cybernetic",
    rarity: "rare",
    equipSlot: "external",
    tags: ["cyber", "drone"],
    cardRefs: ["skip_all_enemies"],
    effects: [{ kind: "stat", vitals: { humanity: -2 }, skills: { subSkills: { engineering: 1 } } }],
    description: "Deploys a temporary net that forces enemies to wait a turn.",
  },
}

export const listItems = () => Object.values(ITEMS)

export const getItemById = (id: string) => ITEMS[id]

export default ITEMS
