// auto-generated by scripts/generate-character-manifest.cjs
import { ImageSourcePropType } from 'react-native'
export type CharacterManifest = Record<string, ImageSourcePropType[]>
const manifest: CharacterManifest = {
  "ACCESSORY": [
    require("../../../src/assets/characters/ACCESSORY/0.png"),
    require("../../../src/assets/characters/ACCESSORY/1.png"),
    require("../../../src/assets/characters/ACCESSORY/2.png"),
    require("../../../src/assets/characters/ACCESSORY/3.png"),
    require("../../../src/assets/characters/ACCESSORY/4.png"),
    require("../../../src/assets/characters/ACCESSORY/5.png"),
    require("../../../src/assets/characters/ACCESSORY/6.png"),
  ],
  "BG": [
    require("../../../src/assets/characters/BG/1.png"),
  ],
  "BODY_BACK": [
    require("../../../src/assets/characters/BODY_BACK/1.png"),
    require("../../../src/assets/characters/BODY_BACK/2.png"),
    require("../../../src/assets/characters/BODY_BACK/3.png"),
    require("../../../src/assets/characters/BODY_BACK/4.png"),
  ],
  "BODY_FRONT": [
    require("../../../src/assets/characters/BODY_FRONT/1.png"),
    require("../../../src/assets/characters/BODY_FRONT/2.png"),
    require("../../../src/assets/characters/BODY_FRONT/3.png"),
    require("../../../src/assets/characters/BODY_FRONT/4.png"),
  ],
  "BODY_INNER": [
    require("../../../src/assets/characters/BODY_INNER/1.png"),
    require("../../../src/assets/characters/BODY_INNER/2.png"),
    require("../../../src/assets/characters/BODY_INNER/3.png"),
  ],
  "EYEBROWS": [
    require("../../../src/assets/characters/EYEBROWS/1.png"),
    require("../../../src/assets/characters/EYEBROWS/2.png"),
    require("../../../src/assets/characters/EYEBROWS/3.png"),
  ],
  "EYES": [
    require("../../../src/assets/characters/EYES/1.png"),
    require("../../../src/assets/characters/EYES/2.png"),
    require("../../../src/assets/characters/EYES/3.png"),
    require("../../../src/assets/characters/EYES/4.png"),
    require("../../../src/assets/characters/EYES/5.png"),
    require("../../../src/assets/characters/EYES/6.png"),
  ],
  "H_ACCESSORY": [
    require("../../../src/assets/characters/H_ACCESSORY/0.png"),
    require("../../../src/assets/characters/H_ACCESSORY/1.png"),
    require("../../../src/assets/characters/H_ACCESSORY/2.png"),
    require("../../../src/assets/characters/H_ACCESSORY/3.png"),
    require("../../../src/assets/characters/H_ACCESSORY/4.png"),
    require("../../../src/assets/characters/H_ACCESSORY/5.png"),
  ],
  "H_BACK": [
    require("../../../src/assets/characters/H_BACK/1.png"),
    require("../../../src/assets/characters/H_BACK/2.png"),
  ],
  "H_FRONT": [
    require("../../../src/assets/characters/H_FRONT/1.png"),
    require("../../../src/assets/characters/H_FRONT/2.png"),
    require("../../../src/assets/characters/H_FRONT/3.png"),
  ],
  "H_SIDE": [
    require("../../../src/assets/characters/H_SIDE/0.png"),
    require("../../../src/assets/characters/H_SIDE/2.png"),
  ],
  "MOUTH": [
    require("../../../src/assets/characters/MOUTH/1.png"),
    require("../../../src/assets/characters/MOUTH/10.png"),
    require("../../../src/assets/characters/MOUTH/11.png"),
    require("../../../src/assets/characters/MOUTH/2.png"),
    require("../../../src/assets/characters/MOUTH/3.png"),
    require("../../../src/assets/characters/MOUTH/4.png"),
    require("../../../src/assets/characters/MOUTH/5.png"),
    require("../../../src/assets/characters/MOUTH/6.png"),
    require("../../../src/assets/characters/MOUTH/7.png"),
    require("../../../src/assets/characters/MOUTH/8.png"),
    require("../../../src/assets/characters/MOUTH/9.png"),
  ],
  "NECK": [
    require("../../../src/assets/characters/NECK/1.png"),
    require("../../../src/assets/characters/NECK/2.png"),
    require("../../../src/assets/characters/NECK/3.png"),
    require("../../../src/assets/characters/NECK/4.png"),
    require("../../../src/assets/characters/NECK/5.png"),
    require("../../../src/assets/characters/NECK/6.png"),
    require("../../../src/assets/characters/NECK/7.png"),
    require("../../../src/assets/characters/NECK/9.png"),
  ],
  "NOSE": [
    require("../../../src/assets/characters/NOSE/1.png"),
    require("../../../src/assets/characters/NOSE/2.png"),
    require("../../../src/assets/characters/NOSE/3.png"),
    require("../../../src/assets/characters/NOSE/4.png"),
    require("../../../src/assets/characters/NOSE/5.png"),
  ],
  "SHAPE": [
    require("../../../src/assets/characters/SHAPE/1.png"),
    require("../../../src/assets/characters/SHAPE/2.png"),
    require("../../../src/assets/characters/SHAPE/3.png"),
    require("../../../src/assets/characters/SHAPE/4.png"),
    require("../../../src/assets/characters/SHAPE/5.png"),
    require("../../../src/assets/characters/SHAPE/6.png"),
  ],
}
export default manifest