import { StyleSheet } from "react-native"
import { FACES, GRID_CARD_HEIGHT, GRID_CARD_WIDTH, GRID_GAP, ITEM_ICON_SIZE, SCREEN_WIDTH } from "./profilePanelConstants"

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0c0f18",
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: "#1d2435",
    position: "relative",
    justifyContent: "space-between",
  },
  content: {
    flex: 1,
    justifyContent: "flex-end",
  },
  selectionPanel: {
    flexDirection: "row",
    alignItems: "flex-start",
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#2b3a55",
    backgroundColor: "#0f1722",
    marginBottom: 8,
    height: "30%",
    width: "100%",
  },
  selectionSideColumn: {
    alignItems: "center",
    marginRight: 10,
    gap: 8,
  },
  selectionIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 8,
    backgroundColor: "#161e30",
    alignItems: "center",
    justifyContent: "center",
  },
  selectionIconCanvas: {
    width: "100%",
    height: "100%",
  },
  selectionTextWrap: { flex: 1, justifyContent: "flex-start", gap: 4 },
  selectionTitleRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  selectionTitle: { color: "#f5f6fb", fontFamily: FACES.BOLD, fontSize: 14 },
  selectionDesc: { color: "#c6cedd", fontSize: 11, lineHeight: 16, flexShrink: 1 },
  selectionStats: { gap: 3 },
  selectionStatText: { color: "#8eb6ff", fontSize: 11 },
  selectionButton: {
    width: 64,
    height: 64,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2b3a55",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#131d2f",
  },
  cardStrip: { gap: 10, paddingVertical: 4 },
  selectionCardRow: {
    width: 220,
    borderWidth: 1,
    borderRadius: 10,
    padding: 8,
    backgroundColor: "#111624",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    height: 78,
  },
  selectionCardBadgeLeft: {
    position: "absolute",
    top: 6,
    left: 6,
    width: 24,
    height: 24,
    borderRadius: 6,
    backgroundColor: "#1a2336",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#2b3a55",
  },
  selectionCardBadgeRight: {
    position: "absolute",
    top: 6,
    right: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: "#1a2336",
    borderWidth: 1,
    borderColor: "#2b3a55",
  },
  selectionCardIcon: {
    width: ITEM_ICON_SIZE + 6,
    height: ITEM_ICON_SIZE + 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2b3a55",
    backgroundColor: "#121b2b",
    alignItems: "center",
    justifyContent: "center",
  },
  selectionCardText: { flex: 1, gap: 2 },
  sortRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  sortButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2b3a55",
    backgroundColor: "#111827",
  },
  sortText: { color: "#cfe1ff", fontFamily: FACES.BOLD, fontSize: 11 },
  filterChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#2b3a55",
    backgroundColor: "#0f1722",
  },
  filterText: { color: "#cfe1ff", fontSize: 10, fontFamily: FACES.REGULAR },
  inventoryList: { flex: 1 },
  inventoryListContent: { paddingBottom: 12, gap: 6 },
  inventoryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#1f2a3f",
    backgroundColor: "#0f1722",
  },
  inventoryRowSelected: { borderColor: "#4ea1ff", backgroundColor: "#14233a" },
  inventoryIconWrap: {
    width: ITEM_ICON_SIZE + 6,
    height: ITEM_ICON_SIZE + 6,
    borderRadius: 8,
    borderWidth: 1,
    backgroundColor: "#121b2b",
    alignItems: "center",
    justifyContent: "center",
  },
  inventoryIconCanvas: { width: ITEM_ICON_SIZE, height: ITEM_ICON_SIZE },
  inventoryTypeIcon: {
    width: 28,
    height: 28,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#2b3a55",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#101827",
  },
  inventoryTextWrap: { flex: 1, gap: 2 },
  inventoryName: { color: "#f5f6fb", fontFamily: FACES.BOLD, fontSize: 12 },
  inventoryMeta: { color: "#9aa6bf", fontSize: 10, fontFamily: FACES.REGULAR },
  equipButton: {
    width: 30,
    height: 30,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#2b3a55",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#131d2f",
  },
  equipButtonActive: { borderColor: "#ff6b6b" },
  equipButtonDisabled: { opacity: 0.4 },
  equipRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
  },
  cyberRowWrap: {
    width: "100%",
  },
  cyberLabelRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  cyberSlotsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  cyberBucket: {
    alignItems: "center",
  },
  cyberBucketLabel: {
    color: "#9aa6bf",
    fontSize: 6,
    textAlign: "center",
    fontFamily: FACES.BOLD,
  },
  cyberBucketSlots: {
    flexDirection: "row",
    justifyContent: "center",
  },
  cyberSlotWrap: {
    alignItems: "center",
    width: 48,
  },
  equipSlotWrap: {
    alignItems: "center",
    width: 48,
  },
  equipSlot: {
    width: 44,
    height: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#1e2637",
    backgroundColor: "#0f1722",
    alignItems: "center",
    justifyContent: "center",
  },
  equipSlotActive: {
    borderColor: "#4ea1ff",
    backgroundColor: "#14233a",
  },
  equipLabel: {
    color: "#9aa6bf",
    fontSize: 6,
    textTransform: "capitalize",
    marginBottom: 4,
  },
  trashSlot: {
    backgroundColor: "#ff4d4d",
    borderColor: "#2d0b0b",
  },
  slotIconWrap: {
    width: ITEM_ICON_SIZE + 4,
    height: ITEM_ICON_SIZE + 4,
    borderRadius: 8,
    borderWidth: 1,
    backgroundColor: "#121b2b",
    alignItems: "center",
    justifyContent: "center",
  },
  slotIconCanvas: { width: ITEM_ICON_SIZE, height: ITEM_ICON_SIZE },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 12,
  },
  toggleButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 10,
    minHeight: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2b3a55",
    backgroundColor: "#111827",
    width: "100%",
  },
  toggleButtonWrap: {
    flex: 1,
  },
  toggleActive: {
    backgroundColor: "#162033",
    borderColor: "#4ea1ff",
  },
  toggleText: {
    color: "#cfe1ff",
    fontSize: 11,
    fontFamily: FACES.BOLD,
    textAlign: "center",
  },
  toggleTextActive: {
    color: "#cfe1ff",
  },
  list: { gap: 10 },
  listContent: { paddingBottom: 12, gap: 8 },
  empty: { color: "#8e93a8" },
  deckControls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
    gap: 8,
  },
  deckToggleButton: {
    width: 36,
    height: 36,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2b3a55",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#111827",
  },
  deckSortButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2b3a55",
    backgroundColor: "#111827",
  },
  deckSortText: { color: "#cfe1ff", fontFamily: FACES.BOLD, fontSize: 11 },
  deckListRow: {
    borderWidth: 1,
    borderRadius: 10,
    padding: 8,
    backgroundColor: "#111624",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    height: 86,
  },
  deckListCostBadge: {
    position: "absolute",
    top: 6,
    right: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    backgroundColor: "rgba(0,0,0,0.6)",
    borderWidth: 1,
    borderColor: "#2b3a55",
  },
  deckListCountBadge: {
    position: "absolute",
    bottom: 6,
    right: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: "rgba(0,0,0,0.6)",
    borderWidth: 1,
    borderColor: "#2b3a55",
  },
  deckCostText: { color: "#cfe1ff", fontFamily: FACES.BOLD, fontSize: 11 },
  deckSourceColumn: { alignItems: "center", width: ITEM_ICON_SIZE + 10, gap: 4 },
  deckSourceName: { color: "#9aa6bf", fontSize: 6, textAlign: "center" },
  sourceIconWrap: {
    width: ITEM_ICON_SIZE + 6,
    height: ITEM_ICON_SIZE + 6,
    borderRadius: 8,
    borderWidth: 1,
    backgroundColor: "#121b2b",
    alignItems: "center",
    justifyContent: "center",
  },
  sourceIconCanvas: { width: ITEM_ICON_SIZE, height: ITEM_ICON_SIZE },
  deckTextWrap: { flex: 1, gap: 2 },
  deckTitleRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  deckCardTitle: { color: "#f2f3f7", fontFamily: FACES.BOLD, fontSize: 12 },
  deckCardDesc: { color: "#c9cdd8", fontSize: 10, lineHeight: 14 },
  countBadgeText: { color: "#cfe1ff", fontSize: 10, fontFamily: FACES.BOLD },
  deckGrid: {
    gap: GRID_GAP,
    paddingBottom: 12,
    alignItems: "center",
  },
  deckGridRow: { gap: GRID_GAP, justifyContent: "center" },
  deckGridCard: {
    borderRadius: 12,
    borderWidth: 1,
    backgroundColor: "#0f1722",
    overflow: "hidden",
  },
  gridCardArt: { flex: 1, alignItems: "center", justifyContent: "center" },
  gridCardCanvas: { flex: 1 },
  gridCardFooter: { paddingHorizontal: 6, paddingVertical: 4, borderTopWidth: 1, borderTopColor: "#1e2637" },
  gridCardTitle: { color: "#f5f6fb", fontFamily: FACES.BOLD, fontSize: 10 },
  gridCardMeta: { color: "#9aa6bf", fontSize: 9 },
  gridCountBadge: {
    position: "absolute",
    top: 6,
    right: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: "rgba(0,0,0,0.6)",
    borderWidth: 1,
    borderColor: "#2b3a55",
  },
  gridCountText: { color: "#fff", fontSize: 9, fontFamily: FACES.BOLD },
  gridCostBadge: {
    position: "absolute",
    top: 6,
    left: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    backgroundColor: "rgba(0,0,0,0.6)",
    borderWidth: 1,
    borderColor: "#2b3a55",
  },
  gridCostText: { color: "#fff", fontSize: 9, fontFamily: FACES.BOLD },
  cardModalOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(0,0,0,0.7)", alignItems: "center", justifyContent: "center" },
  cardModal: { width: SCREEN_WIDTH - 60, backgroundColor: "#0b0d16", borderRadius: 14, padding: 14, borderWidth: 1, borderColor: "#1f2738", gap: 8 },
      width: "100%",
  cardModalCanvas: { width: 180, height: 180 },
    toggleButtonWrap: {
      flex: 1,
    },
  cardModalTitle: { color: "#fff", fontFamily: FACES.BOLD, fontSize: 16 },
  cardModalMeta: { color: "#9aa1b5", fontFamily: FACES.REGULAR, fontSize: 12 },
  cardModalDesc: { color: "#cdd4e5", fontFamily: FACES.REGULAR, fontSize: 12 },
  deckGridCardSize: { width: GRID_CARD_WIDTH, height: GRID_CARD_HEIGHT },
})

export default styles
